# Generated by Django 4.2 on 2026-06-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_doctorleave_doctoravailability"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="doctorleave",
            unique_together={("doctor", "leave_date")},
        ),
    ]
