# Generated by Django 4.2 on 2026-06-20 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_alter_doctorleave_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="doctoravailability",
            unique_together={("doctor", "working_day")},
        ),
    ]
