# Generated by Django 4.2 on 2026-06-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="consultation_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
