# Generated by Django 4.2 on 2026-06-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClinicSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clinic_name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=15)),
                (
                    "slot_duration",
                    models.IntegerField(
                        choices=[
                            (15, "15 Minutes"),
                            (30, "30 Minutes"),
                            (45, "45 Minutes"),
                        ],
                        default=30,
                    ),
                ),
            ],
        ),
    ]
